// GENERATED by scripts/art_manifest.ts from public/art/** — do not edit by hand.
// Painted illustrations (Nous Portal image models, see art/gen/STYLE.md). UI shows the illustration
// when the manifest has the id, otherwise falls back to the procedural SVG CardArt.

export type ArtKind = 'leaders' | 'doctrines' | 'edicts' | 'crises' | 'omens' | 'reforms' | 'eras' | 'key';
export type BackdropKind = 'eras' | 'key';

export const ART_KINDS: readonly ArtKind[] = ['leaders', 'doctrines', 'edicts', 'crises', 'omens', 'reforms', 'eras', 'key'];

/** Pixel size of every shipped file per kind (portrait variants of backdrops are the transpose). */
export const ART_SIZE: Readonly<Record<ArtKind, { w: number; h: number }>> = {
  leaders: { w: 640, h: 800 },
  doctrines: { w: 512, h: 512 },
  edicts: { w: 512, h: 512 },
  crises: { w: 512, h: 512 },
  omens: { w: 512, h: 512 },
  reforms: { w: 512, h: 512 },
  eras: { w: 1600, h: 900 },
  key: { w: 1600, h: 900 },
};

/** 1 = single image, 2 = landscape + `-portrait` variant. */
const FILES: Readonly<Record<ArtKind, Readonly<Record<string, 1 | 2>>>> = {
  leaders: {
    'ashkari': 1,
    'aurelian': 1,
    'celestine': 1,
    'kethran': 1,
    'morvane': 1,
    'sylvaran': 1,
    'thalassan': 1,
    'varkhan': 1,
  },
  doctrines: {},
  edicts: {},
  crises: {},
  omens: {},
  reforms: {},
  eras: {
    '0': 2,
    '1': 2,
    '2': 2,
    '3': 2,
    '4': 2,
    '5': 2,
  },
  key: {
    'defeat': 2,
    'menu': 2,
    'victory': 2,
  },
};

export interface ArtEntry {
  kind: ArtKind;
  id: string;
  src: string;
  /** portrait (900×1600) variant for backdrop kinds, when shipped */
  portrait: string | null;
}

const BASE = import.meta.env.BASE_URL;
const url = (kind: ArtKind, file: string) => `${BASE}art/${kind}/${file}.webp`;

/** Every shipped illustration, in kind order then id order. */
export const ART_LIST: readonly ArtEntry[] = ART_KINDS.flatMap((kind) =>
  Object.entries(FILES[kind]).map(([id, n]) => ({
    kind, id, src: url(kind, id), portrait: n === 2 ? url(kind, id + '-portrait') : null,
  })),
);

/** URL of the illustration for a content id (landscape for backdrop kinds), or null if none shipped. */
export function artFor(kind: ArtKind, id: string): string | null {
  return Object.hasOwn(FILES[kind], id) ? url(kind, id) : null;
}

/** Backdrop URL matched to the viewport orientation; falls back to the landscape image. */
export function backdropFor(kind: BackdropKind, id: string, portrait: boolean): string | null {
  if (!Object.hasOwn(FILES[kind], id)) return null;
  return portrait && FILES[kind][id] === 2 ? url(kind, id + '-portrait') : url(kind, id);
}

/** Ids with an illustration for a kind. */
export function artIds(kind: ArtKind): string[] {
  return Object.keys(FILES[kind]);
}
