// OWNER: ContentRogue. Mars hazards that cap each era's final Sol Report chapter.
import type { CrisisDef, HookCtx } from '../sim/defs';
import { changePop, citiesOf } from '../sim/cities';
import { spawnStorm, changeCryo } from '../sim/mars';
import { pick } from '../sim/rng';
import { BARBARIAN, YIELD_KEYS } from '../sim/types';
import { createUnit } from '../sim/units';
import { hexDistance } from '../sim/hex';

function warn(ctx: HookCtx, text: string, icon = 'storm'): void {
  ctx.emit({ type: 'notify', text, icon, tone: 'bad' });
}
function spawnFerals(ctx: HookCtx): void {
  const cities = citiesOf(ctx.state, ctx.player.id);
  if (!cities.length) return;
  const occupied = new Set(Object.values(ctx.state.units).map((unit) => unit.tile));
  const candidates = ctx.state.map.tiles.filter((tile) =>
    tile.owner === null && !tile.camp && tile.elevation !== 'mountain' &&
    !['coast', 'ocean', 'lake'].includes(tile.terrain) && !occupied.has(tile.idx) &&
    cities.every((city) => hexDistance(ctx.state.map, city.tile, tile.idx) > 2)
  );
  if (candidates.length) createUnit(ctx.state, BARBARIAN, 'warrior', pick(ctx.state.rng, candidates).idx, ctx.emit);
}

const LIST: CrisisDef[] = [
  { id: 'long_winter', name: 'Polar Night', eras: [0, 1], reward: 4, affectsAll: true, icon: 'moon', art: { hue: 205, motif: 'mountain' }, description: 'Frost Plains and Ice Cap tiles give nothing. {food} is **25%** lower in every colony.', flavor: 'The sun stays far away. It does not like the cold either.', effects: { onBegin(ctx) { warn(ctx, 'Polar Night: the cold hits your colonies.', 'moon'); }, tileYield(_ctx, a) { if (a.tile.terrain === 'tundra' || a.tile.terrain === 'snow') for (const key of YIELD_KEYS) a.yields[key] = 0; }, cityYield(_ctx, a) { a.pct.food -= 25; } } },
  { id: 'steppe_horde', name: 'Raider Uprising', eras: [0, 1, 2], reward: 5, icon: 'skull', art: { hue: 22, motif: 'horse' }, description: 'Raiders appear outside your borders when it starts, and again every 2 turns.', flavor: 'They came early, landed badly, and blame you for it.', effects: { onBegin(ctx) { warn(ctx, 'Raiders are moving outside your borders.', 'skull'); spawnFerals(ctx); }, turnStart(ctx) { if (ctx.state.turn % 2 === 0) spawnFerals(ctx); } } },
  { id: 'great_flood', name: 'Salt Flood', eras: [0, 1], reward: 4, icon: 'wave', art: { hue: 195, motif: 'wave' }, description: 'Every colony makes **25%** less {food}. Salt water gets into the water systems.', flavor: 'The water is wet. It is not safe to drink.', effects: { onBegin(ctx) { warn(ctx, 'Salt Flood: clean every water line.', 'wave'); }, cityYield(_ctx, a) { a.pct.food -= 25; } } },
  { id: 'dark_prophecy', name: 'Signal Failure', eras: [0, 1, 2, 3, 4, 5], reward: 10, targetMul: 1.5, weight: 0.5, icon: 'eye', art: { hue: 275, motif: 'eye' }, description: 'The chapter target is **50%** higher. Pass the chapter to earn **10** Coins.', flavor: 'The numbers are bad. The screen shows them anyway.', effects: { onBegin(ctx) { warn(ctx, 'Signal Failure: your target just got higher.', 'eye'); } } },
  { id: 'schism', name: 'Comms Blackout', eras: [1, 2], reward: 5, icon: 'bolt', art: { hue: 300, motif: 'bolt' }, description: 'Each Research pick shows **1 fewer** choice.', flavor: 'The Shop can hear you. It chooses not to answer.', effects: { onBegin(ctx) { warn(ctx, 'Comms Blackout: you get fewer Research choices.', 'bolt'); }, researchOffers(_ctx, a) { a.value = Math.max(1, a.value - 1); } } },
  { id: 'sea_peoples', name: 'Phobos Debris Shower', eras: [1, 2], reward: 5, icon: 'star', art: { hue: 215, motif: 'star' }, description: 'Debris falls on Mars. Every colony makes **10%** less {prod}.', flavor: 'Phobos is breaking apart. Nobody fixed it in time.', effects: { onBegin(ctx) { warn(ctx, 'Debris warning: take cover.', 'star'); }, cityYield(_ctx, a) { a.pct.prod -= 10; } } },
  { id: 'rival_ascendant', name: 'Rival Landing', eras: [1, 2, 3], reward: 6, icon: 'drop', art: { hue: 0, motif: 'flame' }, description: 'Raiders get **+30%** strength against your units.', flavor: 'Their beacon says “peaceful survey.” Their guns say something else.', effects: { onBegin(ctx) { warn(ctx, 'Raiders took a crashed ship. They are armed and close.', 'war'); }, combat(_ctx, a) { if (a.side === 'attack' ? a.defenderOwner !== BARBARIAN : a.attackerOwner !== BARBARIAN) return; const mods = a.side === 'attack' ? a.defenseMods : a.attackMods; mods.push({ label: 'Rival Landing', pct: 30 }); } } },
  { id: 'plague', name: 'Pod Failure', eras: [2, 3], reward: 6, icon: 'cryo', art: { hue: 88, motif: 'skull' }, description: 'You lose **1 Pod** when it starts.', flavor: 'The freezer alarm rings for hours. That is a bad sign.', effects: { onBegin(ctx) { changeCryo(ctx.state, ctx.player.id, -1, ctx.emit); warn(ctx, 'Pod Failure: one Pod is lost.', 'cryo'); } } },
  { id: 'iconoclasm', name: 'Toxic Bloom', eras: [2, 3], reward: 6, icon: 'skull', art: { hue: 35, motif: 'serpent' }, description: 'Every colony makes **20%** less {food}.', flavor: 'The soil looks rich. Nothing wants to grow in it.', effects: { onBegin(ctx) { warn(ctx, 'Toxic Bloom: clean the filters now.', 'skull'); }, cityYield(_ctx, a) { a.pct.food -= 20; } } },
  { id: 'famine', name: 'Crop Blight', eras: [2, 3], reward: 5, affectsAll: true, icon: 'seed', art: { hue: 40, motif: 'tree' }, description: 'Every colony makes **25%** less {food}.', flavor: 'The first tomatoes were great. The last ones were mostly dust.', effects: { onBegin(ctx) { warn(ctx, 'Crop Blight: separate the sick plants.', 'seed'); }, cityYield(_ctx, a) { a.pct.food -= 25; } } },
  { id: 'peasant_revolt', name: 'Air Leak', eras: [3, 4], reward: 6, icon: 'unhappy', art: { hue: 12, motif: 'flame' }, description: 'Every colony loses **15%** {food} and **15%** {prod} to repairs.', flavor: 'The leak was small. The crew is very tired of it.', effects: { onBegin(ctx) { warn(ctx, 'Air leak found. Repairs take time and work.', 'unhappy'); }, cityYield(_ctx, a) { a.pct.food -= 15; a.pct.prod -= 15; } } },
  { id: 'comet_omen', name: 'Solar Flare', eras: [3, 4], reward: 6, icon: 'sun', art: { hue: 250, motif: 'sun' }, description: 'Every colony makes **25%** less {sci}.', flavor: 'The Sun sent a message. It was mostly radiation.', effects: { onBegin(ctx) { warn(ctx, 'Solar Flare: protect the instruments.', 'sun'); }, cityYield(_ctx, a) { a.pct.sci -= 25; } } },
  { id: 'debt_crisis', name: 'Orbit Decay', eras: [3, 4], reward: 7, icon: 'drop', art: { hue: 50, motif: 'moon' }, description: 'Each Land Colony costs **1 more Pod**.', flavor: 'The Ark is drifting. Someone used up the fuel.', effects: { onBegin(ctx) { warn(ctx, 'Orbit Decay: each Land Colony now needs one more Pod.', 'drop'); }, dropPrice(_ctx, a) { a.cryo += 1; } } },
  { id: 'trade_collapse', name: 'Supply Collapse', eras: [4, 5], reward: 7, icon: 'coin', art: { hue: 28, motif: 'gear' }, description: 'Every colony makes **35%** less {gold}. Improvements cost **25%** more {gold}.', flavor: 'The cargo plan was good. The cargo never came.', effects: { onBegin(ctx) { warn(ctx, 'Supply Collapse: the cargo ships are empty.', 'coin'); }, cityYield(_ctx, a) { a.pct.gold -= 35; }, cost(_ctx, a) { if (a.currency === 'gold' && a.item.kind === 'improvement') a.cost *= 1.25; } } },
  { id: 'industrial_smog', name: 'Global Dust Storm', eras: [4, 5], reward: 7, affectsAll: true, icon: 'storm', art: { hue: 70, motif: 'mountain' }, description: '**3** extra Dust Storms appear when it starts. Every colony makes **10%** less {food} and {prod}.', flavor: 'The horizon is gone. It was a good horizon.', effects: { onBegin(ctx) { for (let i = 0; i < 3; i++) spawnStorm(ctx.state, { power: 3, radius: 3, great: true }, ctx.emit); warn(ctx, 'Global Dust Storm: you cannot see far.', 'storm'); }, cityYield(_ctx, a) { a.pct.food -= 10; a.pct.prod -= 10; } } },
  { id: 'pandemic', name: 'Water Failure', eras: [4, 5], reward: 7, affectsAll: true, icon: 'wave', art: { hue: 140, motif: 'gear' }, description: 'Colonies without a Water Recycler lose **1** population when it starts.', flavor: 'The water loop is closed. The complaints are not.', effects: { onBegin(ctx) { for (const city of citiesOf(ctx.state, ctx.player.id)) if (!city.buildings.includes('aqueduct') && city.pop > 1) changePop(ctx.state, city, -1, ctx.emit); warn(ctx, 'Water Failure: use water with care.', 'wave'); } } },
  { id: 'world_war', name: 'Raider Arsenal', eras: [4, 5], reward: 8, icon: 'war', art: { hue: 355, motif: 'sword' }, description: 'Military units cost **25%** more {prod}.', flavor: 'The Raiders found the weapons store. It was not locked.', effects: { onBegin(ctx) { warn(ctx, 'Raider Arsenal: the Raiders are well armed now.', 'war'); }, cost(_ctx, a) { if (a.currency === 'prod' && a.item.kind === 'unit') a.cost *= 1.25; } } },
  { id: 'nuclear_standoff', name: 'Earth’s Last Broadcast', eras: [5], reward: 8, icon: 'hourglass', art: { hue: 15, motif: 'eye' }, description: 'Every colony makes **25%** less {sci}.', flavor: 'A voice from Earth, lost in noise and thirty years of bad news.', effects: { onBegin(ctx) { warn(ctx, 'Earth’s Last Broadcast blocks every channel.', 'hourglass'); }, cityYield(_ctx, a) { a.pct.sci -= 25; } } },
  { id: 'great_blackout', name: 'Power Failure', eras: [5], reward: 8, icon: 'bolt', art: { hue: 230, motif: 'bolt' }, description: 'Colonies without a Fusion Plant make **30%** less {prod} and {sci}.', flavor: 'The reactor shut itself down. It was the smart thing to do.', effects: { onBegin(ctx) { warn(ctx, 'Power Failure: backup power is not enough.', 'bolt'); }, cityYield(_ctx, a) { if (!a.city.buildings.includes('powerplant')) { a.pct.prod -= 30; a.pct.sci -= 30; } } } },
];

export const CRISES: Record<string, CrisisDef> = Object.fromEntries(LIST.map((crisis) => [crisis.id, crisis]));
