// OWNER: ContentRogue. Mars hazards that cap each era's final Sol Report chapter.
import type { CrisisDef, HookCtx } from '../sim/defs';
import { changePop, citiesOf } from '../sim/cities';
import { spawnStorm, changeCryo } from '../sim/mars';
import { pick } from '../sim/rng';
import { BARBARIAN, HUMAN, YIELD_KEYS } from '../sim/types';
import { createUnit } from '../sim/units';
import { hexDistance } from '../sim/hex';

function warn(ctx: HookCtx, text: string, icon = 'storm'): void {
  ctx.emit({ type: 'notify', text, icon, tone: 'bad' });
}
function spawnFerals(ctx: HookCtx): void {
  const cities = citiesOf(ctx.state, ctx.player.id);
  if (!cities.length) return;
  const occupied = new Set(Object.values(ctx.state.units).map((unit) => unit.tile));
  const candidates = ctx.state.map.tiles.filter((tile) =>
    tile.owner === null && !tile.camp && tile.elevation !== 'mountain' &&
    !['coast', 'ocean', 'lake'].includes(tile.terrain) && !occupied.has(tile.idx) &&
    cities.every((city) => hexDistance(ctx.state.map, city.tile, tile.idx) > 2)
  );
  if (candidates.length) createUnit(ctx.state, BARBARIAN, 'warrior', pick(ctx.state.rng, candidates).idx, ctx.emit);
}

const LIST: CrisisDef[] = [
  { id: 'long_winter', name: 'Polar Night', eras: [0, 1], reward: 4, affectsAll: true, icon: 'moon', art: { hue: 205, motif: 'mountain' }, description: 'Frost Flats and Polar Ice yield nothing; colony Food is **−25%**.', flavor: 'The sun kept its distance. It had heard about the heating bill.', effects: { onBegin(ctx) { warn(ctx, 'Polar Night: the cold has entered the ledger.', 'moon'); }, tileYield(_ctx, a) { if (a.tile.terrain === 'tundra' || a.tile.terrain === 'snow') for (const key of YIELD_KEYS) a.yields[key] = 0; }, cityYield(_ctx, a) { a.pct.food -= 25; } } },
  { id: 'steppe_horde', name: 'Feral Uprising', eras: [0, 1, 2], reward: 5, icon: 'skull', art: { hue: 22, motif: 'horse' }, description: 'Feral raiders gather beyond your borders at the start and every other turn.', flavor: 'They came early, landed badly, and decided that was your fault.', effects: { onBegin(ctx) { warn(ctx, 'Ferals are moving outside your perimeter.', 'skull'); spawnFerals(ctx); }, turnStart(ctx) { if (ctx.state.turn % 2 === 0) spawnFerals(ctx); } } },
  { id: 'great_flood', name: 'Brine Surge', eras: [0, 1], reward: 4, icon: 'wave', art: { hue: 195, motif: 'wave' }, description: 'Colonies lose **25% Food** as brine systems contaminate the water reclaimers.', flavor: 'The brine was technically liquid. It was not technically drinkable.', effects: { onBegin(ctx) { warn(ctx, 'Brine Surge: flush every line and pretend this was planned.', 'wave'); }, cityYield(_ctx, a) { a.pct.food -= 25; } } },
  { id: 'dark_prophecy', name: 'Telemetry Failure', eras: [0, 1, 2, 3, 4, 5], reward: 10, targetMul: 1.5, weight: 0.5, icon: 'eye', art: { hue: 275, motif: 'eye' }, description: 'Sol Report target is **+50%**. Survive and earn **10 Scrip**.', flavor: 'The numbers are bad. The dashboard has stopped pretending otherwise.', effects: { onBegin(ctx) { warn(ctx, 'Telemetry Failure: your target just got ambitious.', 'eye'); } } },
  { id: 'schism', name: 'Comms Blackout', eras: [1, 2], reward: 5, icon: 'bolt', art: { hue: 300, motif: 'bolt' }, description: 'The Breakthrough draft shows **1 fewer** research option.', flavor: 'The Uplink can hear you. It has chosen not to answer.', effects: { onBegin(ctx) { warn(ctx, 'Comms Blackout: the Uplink is rationing research options.', 'bolt'); }, researchOffers(_ctx, a) { a.value = Math.max(1, a.value - 1); } } },
  { id: 'sea_peoples', name: 'Phobos Debris Shower', eras: [1, 2], reward: 5, icon: 'star', art: { hue: 215, motif: 'star' }, description: 'Orbital debris strikes colony systems: every city loses **10% Industry**.', flavor: 'Phobos is coming apart. Nobody filed a maintenance ticket.', effects: { onBegin(ctx) { warn(ctx, 'Debris warning: get under something expensive.', 'star'); }, cityYield(_ctx, a) { a.pct.prod -= 10; } } },
  { id: 'rival_ascendant', name: 'Rival Landing', eras: [1, 2, 3], reward: 6, icon: 'drop', art: { hue: 0, motif: 'flame' }, description: 'A rival gets **+30% combat strength** against your forces this chapter.', flavor: 'Their landing beacon says “peaceful survey.” Their guns say otherwise.', effects: { onBegin(ctx) { warn(ctx, 'A rival Ark has landed within striking distance.', 'war'); }, combat(_ctx, a) { if (a.attackerOwner !== HUMAN && a.defenderOwner !== HUMAN) return; const mods = a.side === 'attack' ? a.defenseMods : a.attackMods; mods.push({ label: 'Rival Landing', pct: 30 }); } } },
  { id: 'plague', name: 'Cryo Bay Failure', eras: [2, 3], reward: 6, icon: 'cryo', art: { hue: 88, motif: 'skull' }, description: 'The Ark loses **1 Cryo pod** when the failure begins.', flavor: 'The freezer alarm has been screaming for three hours. That is not a good sign.', effects: { onBegin(ctx) { changeCryo(ctx.state, ctx.player.id, -1, ctx.emit); warn(ctx, 'Cryo Bay Failure: one pod is gone. Do not check the serial number.', 'cryo'); } } },
  { id: 'iconoclasm', name: 'Perchlorate Bloom', eras: [2, 3], reward: 6, icon: 'skull', art: { hue: 35, motif: 'serpent' }, description: 'Food output is **−20%** in every colony.', flavor: 'The soil is fertile in the same way a battery is a beverage.', effects: { onBegin(ctx) { warn(ctx, 'Perchlorate Bloom: scrub the filters before anyone gets clever.', 'skull'); }, cityYield(_ctx, a) { a.pct.food -= 20; } } },
  { id: 'famine', name: 'Greenhouse Blight', eras: [2, 3], reward: 5, affectsAll: true, icon: 'seed', art: { hue: 40, motif: 'tree' }, description: 'Food is **−25%** in every colony; seed stock is failing across Mars.', flavor: 'The first tomatoes were delicious. The last ones were mostly paperwork.', effects: { onBegin(ctx) { warn(ctx, 'Greenhouse Blight: isolate the affected trays.', 'seed'); }, cityYield(_ctx, a) { a.pct.food -= 25; } } },
  { id: 'peasant_revolt', name: 'Hab Pressure Leak', eras: [3, 4], reward: 6, icon: 'unhappy', art: { hue: 12, motif: 'flame' }, description: 'Every colony loses **15% Food** and **15% Industry** to emergency repairs.', flavor: 'The leak was small. So was the crew’s remaining patience.', effects: { onBegin(ctx) { warn(ctx, 'Pressure leak reported. The crew has requested a less literal workplace.', 'unhappy'); }, cityYield(_ctx, a) { a.pct.food -= 15; a.pct.prod -= 15; } } },
  { id: 'comet_omen', name: 'Solar Particle Event', eras: [3, 4], reward: 6, icon: 'sun', art: { hue: 250, motif: 'sun' }, description: 'Research output is **−25%** while the solar event scrambles instruments.', flavor: 'The Sun sent a memo. It was mostly radiation.', effects: { onBegin(ctx) { warn(ctx, 'Solar Particle Event: shield the instruments.', 'sun'); }, cityYield(_ctx, a) { a.pct.sci -= 25; } } },
  { id: 'debt_crisis', name: 'Ark Orbit Decay', eras: [3, 4], reward: 7, icon: 'drop', art: { hue: 50, motif: 'moon' }, description: 'Orbital Drops cost **1 additional Cryo pod** this chapter.', flavor: 'The Ark is drifting. Somebody has been spending the station-keeping budget.', effects: { onBegin(ctx) { warn(ctx, 'Ark Orbit Decay: every Drop now needs another pod.', 'drop'); }, dropPrice(_ctx, a) { a.cryo += 1; } } },
  { id: 'trade_collapse', name: 'Supply Chain Collapse', eras: [4, 5], reward: 7, icon: 'coin', art: { hue: 28, motif: 'gear' }, description: 'Credits are **−35%** in every colony; installations cost **+25% Credits**.', flavor: 'The cargo schedule was optimistic. The cargo was not there.', effects: { onBegin(ctx) { warn(ctx, 'Supply chain collapse: barter is back, and nobody brought anything.', 'coin'); }, cityYield(_ctx, a) { a.pct.gold -= 35; }, cost(_ctx, a) { if (a.currency === 'gold' && a.item.kind === 'improvement') a.cost *= 1.25; } } },
  { id: 'industrial_smog', name: 'Global Dust Storm', eras: [4, 5], reward: 7, affectsAll: true, icon: 'storm', art: { hue: 70, motif: 'mountain' }, description: 'Great storms batter Mars. **3** extra storm cells spawn at the start of the Crisis.', flavor: 'The horizon is gone. The horizon had a good run.', effects: { onBegin(ctx) { for (let i = 0; i < 3; i++) spawnStorm(ctx.state, { power: 3, radius: 3, great: true }, ctx.emit); warn(ctx, 'Global Dust Storm: visibility is now a luxury.', 'storm'); }, cityYield(_ctx, a) { a.pct.food -= 10; a.pct.prod -= 10; } } },
  { id: 'pandemic', name: 'Water Reclaimer Failure', eras: [4, 5], reward: 7, affectsAll: true, icon: 'wave', art: { hue: 140, motif: 'gear' }, description: 'Colonies without a Water Reclaimer lose **1 population** at chapter start.', flavor: 'The water loop is closed. The complaint loop is not.', effects: { onBegin(ctx) { for (const city of citiesOf(ctx.state, ctx.player.id)) if (!city.buildings.includes('aqueduct') && city.pop > 1) changePop(ctx.state, city, -1, ctx.emit); warn(ctx, 'Water Reclaimer Failure: ration carefully.', 'wave'); } } },
  { id: 'world_war', name: 'Feral Armory Seizure', eras: [4, 5], reward: 8, icon: 'war', art: { hue: 355, motif: 'sword' }, description: 'Military units cost **+25% Industry** to produce.', flavor: 'The ferals have discovered the armory. The armory was not locked.', effects: { onBegin(ctx) { warn(ctx, 'Feral Armory Seizure: the perimeter is under pressure.', 'war'); }, cost(_ctx, a) { if (a.currency === 'prod' && a.item.kind === 'unit') a.cost *= 1.25; } } },
  { id: 'nuclear_standoff', name: 'Earth’s Last Broadcast', eras: [5], reward: 8, icon: 'hourglass', art: { hue: 15, motif: 'eye' }, description: 'All colonies suffer **−25% Data** while the last transmission monopolizes the arrays.', flavor: 'A voice from Earth, buried under static and thirty years of bad news.', effects: { onBegin(ctx) { warn(ctx, 'Earth’s Last Broadcast has interrupted every channel.', 'hourglass'); }, cityYield(_ctx, a) { a.pct.sci -= 25; } } },
  { id: 'great_blackout', name: 'Reactor Scram', eras: [5], reward: 8, icon: 'bolt', art: { hue: 230, motif: 'bolt' }, description: 'Colonies without a Fusion Plant suffer **−30% Industry and Data**.', flavor: 'The reactor shut itself down. It was the most sensible thing anyone did today.', effects: { onBegin(ctx) { warn(ctx, 'Reactor Scram: auxiliary power is carrying the day.', 'bolt'); }, cityYield(_ctx, a) { if (!a.city.buildings.includes('powerplant')) { a.pct.prod -= 30; a.pct.sci -= 30; } } } },
];

export const CRISES: Record<string, CrisisDef> = Object.fromEntries(LIST.map((crisis) => [crisis.id, crisis]));
