// Generates src/ui/art/logoGlyphs.ts: vector outlines of the AEONS wordmark letters, cut from Cinzel Decorative
// (SIL OFL) so the logo is pure SVG paths — no runtime font dependency, crisp at any size, renderable by resvg.
// Run: bun scripts/art2d_logo.ts
import opentype from 'opentype.js';
import { readFileSync, writeFileSync } from 'node:fs';

const FONT = 'node_modules/@fontsource/cinzel-decorative/files/cinzel-decorative-latin-900-normal.woff';
const LETTERS = ['A', 'E', 'O', 'N', 'S'];
const CAP = 100; // output cap-height units

const buf = readFileSync(FONT);
const font = opentype.parse(buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength));
const os2: unknown = font.tables.os2;
const capHeight = os2 && typeof os2 === 'object' && 'sCapHeight' in os2 && typeof os2.sCapHeight === 'number' && os2.sCapHeight > 0 ? os2.sCapHeight : font.unitsPerEm * 0.7;
const scale = CAP / capHeight;

const r1 = (n: number) => Math.round(n * 10) / 10;
function toD(cmds: opentype.PathCommand[]): string {
  let d = '';
  for (const c of cmds) {
    if (c.type === 'M' || c.type === 'L') d += `${c.type}${r1(c.x)} ${r1(c.y)}`;
    else if (c.type === 'Q') d += `Q${r1(c.x1)} ${r1(c.y1)} ${r1(c.x)} ${r1(c.y)}`;
    else if (c.type === 'C') d += `C${r1(c.x1)} ${r1(c.y1)} ${r1(c.x2)} ${r1(c.y2)} ${r1(c.x)} ${r1(c.y)}`;
    else d += 'Z';
  }
  return d;
}

const out: Record<string, { d: string; adv: number; x0: number; x1: number }> = {};
for (const ch of LETTERS) {
  const glyph = font.charToGlyph(ch);
  const path = glyph.getPath(0, CAP, font.unitsPerEm * scale);
  const bb = path.getBoundingBox();
  out[ch] = {
    d: toD(path.commands),
    adv: Math.round((glyph.advanceWidth ?? 0) * scale * 10) / 10,
    x0: Math.round(bb.x1 * 10) / 10,
    x1: Math.round(bb.x2 * 10) / 10,
  };
}

const src = `// GENERATED by scripts/art2d_logo.ts from Cinzel Decorative Black (SIL Open Font License) — do not edit.
// Letter outlines on a ${CAP}-unit cap height, baseline at y=${CAP}; x0/x1 = ink bounds, adv = advance width.
export const LOGO_GLYPHS = ${JSON.stringify(out, null, 2)} as const;
`;
writeFileSync('src/ui/art/logoGlyphs.ts', src);
console.log(Object.fromEntries(Object.entries(out).map(([k, v]) => [k, { adv: v.adv, x0: v.x0, x1: v.x1, len: v.d.length }])));
