#!/usr/bin/env bun
// Regenerates src/ui/art/artManifest.ts from the WebP files actually present in public/art/<kind>/.
//   bun scripts/art_manifest.ts
// Backdrop kinds (eras, key) ship a landscape `<id>.webp` plus an optional `<id>-portrait.webp`.
import { existsSync, readdirSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

const ROOT = resolve(import.meta.dir, '..');
const PUBLIC_ART = join(ROOT, 'public', 'art');
const OUT = join(ROOT, 'src', 'ui', 'art', 'artManifest.ts');

const KINDS = ['leaders', 'doctrines', 'edicts', 'crises', 'eras', 'key'] as const;
const PORTRAIT_SUFFIX = '-portrait';

const data: Record<string, Record<string, { portrait: boolean }>> = {};
let total = 0;
for (const kind of KINDS) {
  const dir = join(PUBLIC_ART, kind);
  const files = existsSync(dir) ? readdirSync(dir).filter((f) => f.endsWith('.webp')).sort() : [];
  const ids = new Set(files.map((f) => f.slice(0, -5)));
  const entries: Record<string, { portrait: boolean }> = {};
  for (const id of ids) {
    if (id.endsWith(PORTRAIT_SUFFIX) && ids.has(id.slice(0, -PORTRAIT_SUFFIX.length))) continue;
    entries[id] = { portrait: ids.has(id + PORTRAIT_SUFFIX) };
    total++;
  }
  data[kind] = entries;
}

const q = (s: string) => `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
const kindBlock = (kind: string) => {
  const entries = Object.entries(data[kind]);
  if (!entries.length) return `  ${kind}: {},`;
  const rows = entries.map(([id, e]) => `    ${q(id)}: ${e.portrait ? 2 : 1},`);
  return `  ${kind}: {\n${rows.join('\n')}\n  },`;
};

const src = `// GENERATED by scripts/art_manifest.ts from public/art/** — do not edit by hand.
// Painted illustrations (Bankr LLM Gateway, GPT Image 2.5 Flare; see art/gen/STYLE.md). UI shows the illustration
// when the manifest has the id, otherwise falls back to the procedural SVG CardArt.

export type ArtKind = 'leaders' | 'doctrines' | 'edicts' | 'crises' | 'eras' | 'key';
export type BackdropKind = 'eras' | 'key';

export const ART_KINDS: readonly ArtKind[] = ${JSON.stringify(KINDS).replace(/"/g, "'").replace(/,/g, ', ')};

/** Pixel size of every shipped file per kind (portrait variants of backdrops are the transpose). */
export const ART_SIZE: Readonly<Record<ArtKind, { w: number; h: number }>> = {
  leaders: { w: 640, h: 800 },
  doctrines: { w: 512, h: 512 },
  edicts: { w: 512, h: 512 },
  crises: { w: 512, h: 512 },
  eras: { w: 1600, h: 900 },
  key: { w: 1600, h: 900 },
};

/** 1 = single image, 2 = landscape + \`-portrait\` variant. */
const FILES: Readonly<Record<ArtKind, Readonly<Record<string, 1 | 2>>>> = {
${KINDS.map(kindBlock).join('\n')}
};

export interface ArtEntry {
  kind: ArtKind;
  id: string;
  src: string;
  /** portrait (900×1600) variant for backdrop kinds, when shipped */
  portrait: string | null;
}

const BASE = import.meta.env.BASE_URL;
const url = (kind: ArtKind, file: string) => \`\${BASE}art/\${kind}/\${file}.webp\`;

/** Every shipped illustration, in kind order then id order. */
export const ART_LIST: readonly ArtEntry[] = ART_KINDS.flatMap((kind) =>
  Object.entries(FILES[kind]).map(([id, n]) => ({
    kind, id, src: url(kind, id), portrait: n === 2 ? url(kind, id + '${PORTRAIT_SUFFIX}') : null,
  })),
);

/** URL of the illustration for a content id (landscape for backdrop kinds), or null if none shipped. */
export function artFor(kind: ArtKind, id: string): string | null {
  return Object.hasOwn(FILES[kind], id) ? url(kind, id) : null;
}

/** Backdrop URL matched to the viewport orientation; falls back to the landscape image. */
export function backdropFor(kind: BackdropKind, id: string, portrait: boolean): string | null {
  if (!Object.hasOwn(FILES[kind], id)) return null;
  return portrait && FILES[kind][id] === 2 ? url(kind, id + '${PORTRAIT_SUFFIX}') : url(kind, id);
}

/** Ids with an illustration for a kind. */
export function artIds(kind: ArtKind): string[] {
  return Object.keys(FILES[kind]);
}
`;

writeFileSync(OUT, src);
console.log(`artManifest.ts: ${total} illustrations`);
