// OWNER: Roguelite. STUB. Run structure: eras/chapters, chronicle scoring, council, omens, edicts, crises.
import type { Action, ChapterStats, ChronicleResult, DoctrineId, Edition, Emit, GameState, SimEvent } from '../types';

/** fill state.run for a fresh game (after players/map exist); rolls era-0 crisis; phase = 'crisisReveal' */
export function initRun(state: GameState, emit: Emit): void { void state; void emit; throw new Error('not implemented'); }
/** called by engine after every emitted event (stat tracking, omen progress) */
export function trackEvent(state: GameState, ev: SimEvent, emit: Emit): void { void state; void ev; void emit; throw new Error('not implemented'); }
/** engine calls for per-turn aggregates (culture/science/gold generated by the human) */
export function addStat(state: GameState, key: Exclude<keyof ChapterStats, 'extra'>, amount: number): void { void state; void key; void amount; throw new Error('not implemented'); }
/** after all players' end-of-turn processing: advances chapter clock; may compute chronicle & set phase */
export function onTurnEnd(state: GameState, emit: Emit): void { void state; void emit; throw new Error('not implemented'); }
/** handles roguelite actions (ackCrisis, chooseChapterStart, ackChronicle, council*, pack*, doctrine*, edict*, leaveCouncil, continueEndless) — returns error or null */
export function handleRunAction(state: GameState, action: Action, emit: Emit): string | null { void state; void action; void emit; throw new Error('not implemented'); }
export function isRunAction(action: Action): boolean { void action; throw new Error('not implemented'); }
/** which actions are allowed per phase: map actions only in 'playing' */
export function chronicleTarget(state: GameState, era: number, chapter: number): number { void state; void era; void chapter; throw new Error('not implemented'); }
/** pure preview of the chronicle right now (for the HUD "projected Legacy" meter) — must not mutate state */
export function previewChronicle(state: GameState): ChronicleResult { void state; throw new Error('not implemented'); }
export function grantDoctrine(state: GameState, id: DoctrineId, edition: Edition, emit: Emit): string | null { void state; void id; void edition; void emit; throw new Error('not implemented'); }
export function addInfluence(state: GameState, delta: number, emit: Emit): void { void state; void delta; void emit; throw new Error('not implemented'); }
export function changeMandate(state: GameState, delta: number, reason: string, emit: Emit): void { void state; void delta; void reason; void emit; throw new Error('not implemented'); }
